### ISSUE TITLE
Shameless plug for Pure Java HIDAPI

### ISSUE THREAD

**Issue by nyholku** [gary-rowe/hid4java#1]
Hi,

sorry to abuse the issue system and hope you don't mind but I felt that some small group of hid4java users might be interested in a different take on the subject matter and I could not figure out how to reach them.

With the help of reading the HIDAPI code I've managed to put together a Pure Java alternative that requires no native libraries when deployed and no C-tool chain to develop:

You can find it here:

https://github.com/nyholku/purejavahidapi

This is not really an alternative to signal11/HIDAPI as this is Jave or actually JVM only where as HIDAPI is C-API/ABI.

br Kusti

**Comment by ceakins** [comment]
I really strongly urge you to mavenize it. Newbies will have an easier time importing it.

**Comment by nyholku** [comment]
Feel free to contribute a 'pom', I am not up to speed with maven...
