### ISSUE TITLE
Add hidapi 0.10.1

### ISSUE THREAD

**Issue by laborg** [gary-rowe/hid4java#112]
On master hidapi version 0.10.0 is used. A minor release of hidapi 0.10.1 has been issues since then. It would be good if the next release could integrate the minor release.

Thanks for working on hid4java!

**Comment by gary-rowe** [comment]
Agreed. Whenever I do a `hid4java` release I always include the latest `hidapi` release. Things have been busy recently on other projects so progress has slowed a little here.

**Comment by gary-rowe** [comment]
It looks like 0.11.0 is now available so I'll be using that once some issues are resolved (when I can get the time to work on them).

**Comment by gary-rowe** [comment]
I've updated `develop` using `hidapi` 0.12.0 so I'll close this issue.
