### ISSUE TITLE
Benign error when building for Windows ARM64

### ISSUE THREAD

**Issue by tresf** [gary-rowe/hid4java#121]
Windows ARM64 builds show benign error about building `hidtest.exe`.

Since #115 was merged into `issue-93` branch, we can successfully build Windows ARM64 binaries, however reviewing the logs shows there's a build error occuring.  This is a placeholder to fix that error.

```diff
  make[2]: Entering directory '/work/hidtest'
    CCLD     hidtest.exe
- libtool:   error: Could not determine the host path corresponding to
- libtool:   error:   '/work/windows/.libs'
  libtool:   error: Continuing, but uninstalled executables may not work.
  libtool:   error: Could not determine the host path corresponding to
  libtool:   error:   '/work/windows/.libs:/usr/local/lib:/usr/local/bin'
  libtool:   error: Continuing, but uninstalled executables may not work.
  make[2]: Leaving directory '/work/hidtest'
  make[2]: Entering directory '/work'
  make[2]: Leaving directory '/work'
  make[1]: Leaving directory '/work
```

Since the error is very specific to the way `hidapi` is building, I'm not sure if it's a bad assumption in the Makefile or a bug with the `llvm-mingw` wrapper we use, etc.  I've asked for help upstream to see if they can point us in the right direction:

Upstream bug report:
* https://github.com/libusb/hidapi/issues/320

**Comment by gary-rowe** [comment]
Looks like this has been fixed with the recent upgrades to `hidapi` and `dockcross` present in `develop`. Screenshot from the `win32-x86-64` build:

<img width="441" alt="Screenshot 2022-12-05 at 09 43 13" src="https://user-images.githubusercontent.com/342133/205605113-7fc5dc5a-193a-4210-bd1d-6d211b3cca90.png">
