### ISSUE TITLE
Possible incorrect HID packet structure on Windows

### ISSUE THREAD

**Issue by gary-rowe** [gary-rowe/hid4java#13]
Getting reports of failures on Windows. See [MultiBit HD Issue #379](https://github.com/bitcoin-solutions/multibit-hd/issues/379). It could be due to a HID packet misalignment.

**Comment by Metin-Ljapo** [comment]
hi
I had a problem when I tried to build for win 64 bit, the problem was that resource folder is named win32-x86-64 but it was looking for the library under win32-amd64

**Comment by gary-rowe** [comment]
Thanks for the update. I'll add an issue to put the win64 library under that directory for the 0.3.0 release. So many architecture variants to list...

**Comment by gary-rowe** [comment]
Verified that "The parameter is incorrect" message is removed when the report ID of 0x00 is provided with a change to the length of the report in `HidApi`.

**Comment by gary-rowe** [comment]
Verified that this modification works across all platforms.

Closing.
