### ISSUE TITLE
support hidapi 0.14.0

### ISSUE THREAD

**Issue by umjammer** [gary-rowe/hid4java#140]
**Is your feature request related to a problem? Please describe.**

i'd like to use the api `hid_get_report_descriptor` since hidapi 0.14.0.
it seems that the version of hidapi which is included in hid4java (85d76ec) is under 0.14.0.

**Describe the solution you'd like**

update the hidapi version to 0.14.0
and add the api `hid_get_report_descriptor` 

**Additional context**

hid4java: develop-SNAPSHOT (85d76ec)
macos: 13.5.2
java:
```
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment JBR-17.0.8+7-1000.22-jcef (build 17.0.8+7-b1000.22)
OpenJDK 64-Bit Server VM JBR-17.0.8+7-1000.22-jcef (build 17.0.8+7-b1000.22, mixed mode)
```

**Comment by gary-rowe** [comment]
Hi. The latest version of `develop` now supports `hidapi-0.14.0`. There is also a `develop-SNAPSHOT` version available for testing.
