### ISSUE TITLE
Used in systems with security policies:failed to map segment from shared object

### ISSUE THREAD

**Issue by chn-maich** [gary-rowe/hid4java#157]
Due to security policy restrictions on my system, it is not possible to run precompiled files in jar files. Is there a way to configure external dependencies like "jna. library. path"

error:
`ava.lang.UnsatisfiedLinkError: /root/.cache/JNA/temp/jna6456692509398733775.tmp: /root/.cache/JNA/temp/jna6456692509398733775.tmp:failed to map segment from shared object`

**Comment by Masterxilo** [comment]
from the error message it looks like you are running as /root anyways - just disable the policy?
