### ISSUE TITLE
Add better error handling if Hidapi fails

### ISSUE THREAD

**Issue by gary-rowe** [gary-rowe/hid4java#26]
User feedback from the MultiBit HD project (see [Issue 673](https://github.com/bitcoin-solutions/multibit-hd/issues/673)) indicates that hid4java is not handling/informing downstream callers of a failure.

**Comment by gary-rowe** [comment]
I opted to use an early fail fast through the `init()` method to ensure the library load operation occurs correctly, or throws a runtime exception in case of any problems.

Ready for review and close.

**Comment by jim618** [comment]
LGTM.
Closing

**Comment by jim618** [comment]
oh - I cannot close it - must not be a collaborator

**Comment by gary-rowe** [comment]
You are now. Closing.
