### ISSUE TITLE
Classes in root package

### ISSUE THREAD

**Issue by jkropf** [gary-rowe/hid4java#28]
Do not add classes to the default (root) package, this is bad style and causes errors using maven to build projects.
Currently the class UsbHidTrezorV1Example.class is located in the root package.

You can no longer import from default packages. (You used to be able to in Sun's early javac implementations, but this was not allowed for in the language spec.)

**Comment by gary-rowe** [comment]
Clearly this class is only intended for demonstration purposes and should not be referenced in actual use. It is placed there to simplify accessing it outside of an IDE through command line Maven.

That said, your point is well taken. Perhaps the library is mature enough now to move this under src/test/java and into its own example package.

I'll add this to 0.5.0.

**Comment by jkropf** [comment]
Nice, thanks. Otherwise one can't build an application using maven. My
workaround was to delete it from the jar.

Kind regards,
Johannes
Am 16.09.2015 15:58 schrieb "Gary Rowe" <notifications@github.com>:

**Comment by gary-rowe** [comment]
Moved the example around and updated the README as required.

Ready for review and close.

**Comment by andyrozman** [comment]
Either I am looking in at wrong branch or we still have some references to TrezorExample in wrong location in README. Could you please check that, so that I can finish review?

**Comment by gary-rowe** [comment]
Verified the link and Maven execution. Ready to merge.

**Comment by gary-rowe** [comment]
Merged and closed.
