### ISSUE TITLE
Missing linux-arm/libhidapi.so

### ISSUE THREAD

**Issue by jkropf** [gary-rowe/hid4java#29]
In the maven bundle version 0.4.0 there is no native code for arm.  But there is a file "libhidapipi.so" in the root of the jar, shall that be the arm library?

**Comment by gary-rowe** [comment]
Yes, this is present in the develop branch and should be scheduled for 0.5.0.

Since this will occur in the next release, I'll close this issue now.

**Comment by jkropf** [comment]
Great, thx. Yeah, habe also seen it. In the dev branch it would be nice to
have a build.XML for ant or a pom.XML for maven. Just as a suggestion.. :)

Kind regards,
Johannes
Am 16.09.2015 15:55 schrieb "Gary Rowe" <notifications@github.com>:

**Comment by gary-rowe** [comment]
There should be a `pom.xml`. It's all released through the Maven build process.
