### ISSUE TITLE
New version (0.5) and dependencies

### ISSUE THREAD

**Issue by andyrozman** [gary-rowe/hid4java#56]
When is new release planned? 

Would it be possible to upgrade jna dependencies to latest/last 4.x (which would be 4.2.2)? I will do some tests over weekend if it works (at least on linux)...

Andy

**Comment by gary-rowe** [comment]
Hi Andy,

I'm going to block out Saturday morning (UK time) to get a release done and
into Maven. Anything marked as "awaiting merge" will be in that release.

I'll look at updating the JNA dependencies since the project does need
dusting off and modernising.

Cheers,

Gary

**Comment by andyrozman** [comment]
I think that changing jna to latest 4 shouldn't produce any special problems. It would be different if we would try to go with 5.x release, for that we would probably have to make few changes... 

Sorry to be bother, but I am using nrjavaserial for Serial communication in my project and new version has also dependency to jna (4.2.2), and using both libraries with different jna's would never work...

**Comment by gary-rowe** [comment]
Ready for review and merge.

**Comment by gary-rowe** [comment]
Merged and closed.
