### ISSUE TITLE
Vendor_id and product_id bigger or equals to 0x8000 are converted to 0xFFFFXXXX

### ISSUE THREAD

**Issue by aortuno** [gary-rowe/hid4java#65]
Vendor_id and product_id bigger or equals to 0x8000 are converted to 0xFFFF8000, because unsigned short does not exist in Java

**Comment by gary-rowe** [comment]
Will add a bit mask to remove the leading `0xFFFF`.

**Comment by gary-rowe** [comment]
I've added some changes to convert from "unsigned short" to int and added `HidDeviceTest` to verify `0x8001` is correctly matched against `0xffff8001`.

If you have time please review the changes and let me know if you're OK with them.

**Comment by aortuno** [comment]
I tested the new code with 2 devices with "Product Id" bigger than 0x8000, and both works.

**Comment by gary-rowe** [comment]
Thank you - much appreciated! I'll close this issue now and prepare for the 0.6.0 release.
