### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by Vzor-** [gary-rowe/hid4java#69]
Hey, just wondering if you could toss a version number somewhere into the code. Since this is an io library it is nice to be able to programmatically check the version via an api call.

**Comment by andyrozman** [comment]
We could probably generate it in maven, so that artifact version would be
visible in code. I do the same in my project.

**Comment by Vzor-** [comment]
That would be fine, I prefer an in-code version but I'm not picky.

**Comment by gary-rowe** [comment]
Hi! I'll be working on this library starting Mon 16th April in order to release version 0.6.0. I can take a look at this issue then.

**Comment by gary-rowe** [comment]
Added support for this in `develop` branch. Scheduled for release in 0.6.0+.

To test programmatically:
```java
// Use default service settings for example
HidServices hidServices = HidManager.getHidServices();
hidServices.getVersion();
```
To test on `develop` branch:
```bash
mvn clean package
java -cp target/hid4java-develop-SNAPSHOT.jar org.hid4java.HidServices
```
Output should be `develop-SNAPSHOT` or `0.6.0` etc after release on `master`.

**Comment by gary-rowe** [comment]
Closing.
