### ISSUE TITLE
Listener detect new USB device connected [Java/Windows]

### ISSUE THREAD

**Issue by JPizarro14** [gary-rowe/hid4java#70]
Hi!

I'm developing a new project and I need a listener to detect when a USB device has been connected or disconnected. I've been searching different solutions for Java on Windows but I didn't found anything. Is there any possibility to develop that listener using hid4java?

Thank you so much
Best regards

**Comment by gary-rowe** [comment]
Hi! I'll be working on this library starting Mon 16th April in order to release version 0.6.0. I can take a look at this issue then.

**Comment by JPizarro14** [comment]
Hi Gary! Thank you very much! Do you have release date for version 0.6.0?

Best regards

**Comment by gary-rowe** [comment]
The library supports attach/detach events so I think I can close this issue.
