### ISSUE TITLE
getFeatureReport miss the first byte on MacOS

### ISSUE THREAD

**Issue by athenacolin** [gary-rowe/hid4java#75]
When I use getFeatureReport on our HID product on MacOS, I get the result without the first byte. From the code:
System.arraycopy(report.buffer, 1, data, 0, res > data.length ? data.length : res);
it removes the first byte from buffer which it's the message part I want but not reportId.
Could you please point out what I am misunderstanding here?

**Comment by wowneverdie** [comment]
same result on Windows

**Comment by gary-rowe** [comment]
Closing as the method documentation seems clear.
