### ISSUE TITLE
The second connection is not working properly

### ISSUE THREAD

**Issue by WanManito** [gary-rowe/hid4java#88]
In version 0.5.0, I tested read and write normally，
But here's what I did when I tried to free up resources
![image](https://user-images.githubusercontent.com/26118508/74897465-278cd500-53d2-11ea-96dc-5028fe198049.png)

No exception was reported, but when the device was opened again, it was found to be null，as shown below ，
![image](https://user-images.githubusercontent.com/26118508/74897477-2f4c7980-53d2-11ea-87df-043c204b8cc6.png)

The normal situation would be as follows
![image](https://user-images.githubusercontent.com/26118508/74897492-37a4b480-53d2-11ea-81d5-567b6f1bd30e.png)

Strangely enough, after I waited a while, the device was able to connect back to normal

I don't know if I release resources incorrectly or some other reason

**Comment by gary-rowe** [comment]
That looks correct, but it may be that the resources are taking longer to be released than expected. Is it still happening with latest develop-SNAPSHOT version?

**Comment by WanManito** [comment]
I dropped this solution in favor of USB4Java，I don't know if the solution you wrote supports Linux

**Comment by gary-rowe** [comment]
Thanks for getting back to me. hid4java does support Linux but if you've moved on to use usb4java instead then I'll close this issue for now.
