### ISSUE TITLE
Prepare Maven Central release process

### ISSUE THREAD

**Issue by gary-rowe** [gary-rowe/hid4java#9]
This should also cover versions 0.1, 0.2, 0.3 and 0.3.1 for consistency.

**Comment by jitpack** [comment]
Btw, it's also available as a maven dependency at https://jitpack.io/#gary-rowe/hid4java/0.2.0

**Comment by gary-rowe** [comment]
@jitpack Thanks very much :-)

**Comment by pepijndevos** [comment]
Fiiiimally something that does not segfault. It'd be much appreciated if you added tags for releases. I'm now using git hashes with jitpack. But again, great work.

**Comment by gary-rowe** [comment]
@pepijndevos Agreed. You can find each release in the master branch (latest is 0.3.1 which contains important fixes for Windows), but I've been remiss in tagging. I'll look into getting all versions into Maven Central over the weekend.

**Comment by jschneider** [comment]
Come on mate. Give it a shoot and release it to Maven central.
It is not so difficult - but a great help for your fellow users.

**Comment by gary-rowe** [comment]
Yeah - I've released other projects to Maven Central so I've got no excuse other than finding the time to do it. Just so many other things to do...

**Comment by leif81** [comment]
Yes please! :+1:

**Comment by gary-rowe** [comment]
OK, public commitment time. I will block out time this weekend to (finally!) get hid4java into Maven Central (and build the process so that subsequent releases also find their way in too).

Wish me luck.

**Comment by andyrozman** [comment]
Good luck... If you get stuck I will be online this weekend, so I can give advice... You can skype me at (skype:andyrozman)

**Comment by gary-rowe** [comment]
Thanks @andyrozman - should be good for a larf.

**Comment by gary-rowe** [comment]
Well, folks, it's finally in Maven Central. Here's a log:
```
Downloading: http://repo1.maven.org/maven2/org/hid4java/hid4java/0.4.0/hid4java-0.4.0.pom
Downloaded: http://repo1.maven.org/maven2/org/hid4java/hid4java/0.4.0/hid4java-0.4.0.pom (6 KB at 36.0 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/hid4java/hid4java/0.4.0/hid4java-0.4.0.jar
Downloaded: http://repo1.maven.org/maven2/org/hid4java/hid4java/0.4.0/hid4java-0.4.0.jar (188 KB at 1008.1 KB/sec)
```
If people could try their projects using the 0.4.0 version without the mbhd-maven repo reference that would help me to be sure it's all working correctly.

Ready for review and close.

**Comment by leif81** [comment]
I noticed it's showing up now in the search results.

http://search.maven.org/#search%7Cga%7C1%7Chid4java

(I've yet to actually try it though in a project).

**Comment by jschneider** [comment]
Thanks a lot. Great news.

**Comment by gary-rowe** [comment]
Closing now.

**Comment by leif81** [comment]
I added the v0.4.0 artifact from Maven Central into my project and it's working great. Thankyou!

Looking forward to the v0.5.0 release with the native ARM library. :smile:

**Comment by gary-rowe** [comment]
Yeah, I'm expecting 0.5.0 to come out fairly soon. There's a bit of testing for #36 to be completed by people with access to Windows machines but all being well it should be by the end of the month.

**Comment by leif81** [comment]
@gary-rowe Any movement on the 0.5.0 release? :crossed_fingers: :smile:

**Comment by gary-rowe** [comment]
Got a few issues that are pending review. Also I'm just maxed out on other projects at the moment and can't spare the time to work on it.
