### ISSUE TITLE
Meaning of returning value in the "write" method

### ISSUE THREAD

**Issue by permiakovsa** [gary-rowe/hid4java#90]
Hello, there is no explaining of the "write" method in the doc. 
public int write(byte[] message, int packetLength, byte reportId), returns int value, from my experience 5 for success, and -1 for trouble situation. is it correct? is there any more states?

**Comment by nospam2k** [comment]
I'm not sure of this but it seems to me from my testing that the return is just the length of the message + 1 for the reportId.
