### ISSUE TITLE
Inconsistent method names for adding / removing listener

### ISSUE THREAD

**Issue by MorpheusUK** [gary-rowe/hid4java#94]
Hello,

Firstly thanks for producing this library it has made a project i am working on which is running on an older version of SLE Linux far easier. This is quite a trivial one but I notice that when i add the listener I do a addHidServicesListener(HidServicesListener listener). However to remover the listener the method seems to be unless i have misunderstood its purpose removeUsbServicesListener(HidServicesListener listener).

These should be named consistently.

Thanks

**Comment by gary-rowe** [comment]
Agreed. I've made the change in the `develop` branch. Please take a look and let me know if it's OK.

**Comment by MorpheusUK** [comment]
Yes that's great thanks.

**Comment by gary-rowe** [comment]
Cool. Closing.
